apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddev001-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clouddev001
  template:
    metadata:
      labels:
        app: clouddev001
    spec:
      containers:
      - name: web
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/clouddev001:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clouddev001-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: clouddev001