name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: clouddev001
  GKE_ZONE: us-central1-a
  REPOSITORY: clouddev-repo
  REGION: us-central1
  IMAGE_NAME: clouddev001

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Autenticar no GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configurar gcloud e Docker
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Build e Push da Imagem Docker
      run: |
        IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    - name: Deploy no GKE
      run: |
        IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        # Substitui a tag da imagem no manifesto e aplica no cluster
        sed -i "s|LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/clouddev001:latest|$IMAGE_TAG|g" .k8s/deployment.yaml
        kubectl apply -f .k8s/deployment.yaml